### ISSUE TITLE
How to fix protection bypass using Minecart with hopper

### ISSUE THREAD

**Issue by kamil445** [Brokkonaut/LWCEntityLocking#2]
Hi

Is there any way to block this method to steal items from protected chests ?

As player i can steal stuff from chests using this method: https://yal.cc/minecraft-small-large-bug-in-lockette-and-lwc/

I have default LWC config.

I don't want to use plugin like "FriendlyHopper"

Thanks for help!

**Comment by Brokkonaut** [comment]
This issue does not exist when using the default config. Use "denyHoppers: true" in your config (section "protections"), if you do not have it.

**Comment by kamil445** [comment]
EDIT:

I figured out what causing this problem, and problem was because wrong Paper configuration!

IDK why but in paper.yml i have this setting
``
disable-move-event: true
``
set to true, should be false! (false is by default)

Now working without this issue, you can close this issue :)
